services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./stubs/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    networks:
      - app-network
    depends_on:
      - app

  app:
    restart: unless-stopped
    ports:
    - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    build:
      args:
        user: document_lost_admin
        uid: 1000
      context: .
    volumes:
      - .:/var/www/html
      - ./stubs/php.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - app-network

  jobs:
    restart: unless-stopped
    build:
      context: .
      dockerfile: jobs.dockerfile
    volumes:
      - .:/var/www/html
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - app-network

  scheduler:
    restart: unless-stopped
    build:
      args:
        user: document_lost_admin
        uid: 1000
      context: .
      dockerfile: scheduler.dockerfile
    volumes:
      - .:/var/www/html
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: php /var/www/html/artisan schedule:work
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
