SELECT O.ID_OBJETO,
    E.ID_EXTRAVIO,
    E.ID_ESTADO_EXTRAVIO,
    CE.ESTADO_EXTRAVIO,
    IsNull(E.NOMBRE, '') as NOMBRE,
    IsNull(E.PATERNO, '') as PATERNO,
    IsNull(E.MATERNO, '') as MATERNO,
    E.FECHA_EXTRAVIO,
    CAST(E.FECHA_REGISTRO AS DATE) AS FECHA_REGISTRO,
    O.ID_TIPO_DOCUMENTO,
    O.NUMERO_DOCUMENTO,
    O.TITULAR_DOCUMENTO,
    O.ESPECIFIQUE AS TIPO_PLACA,
    H.ID_MUNICIPIO,
    H.ID_LOCALIDAD,
    H.ID_COLONIA,
    H.ID_CALLE,
    O.DESCRIPCION,
    IsNull(CM.MUNICIPIO, '') as MUNICIPIO,
    IsNull(CL.LCLDD,'')AS LOCALIDAD,
    IsNull(CC.CLNIA, '') As COLONIA,
    IsNull(CCA.CLLE, '') AS CALLE
FROM [dbo].[PGJ_OBJETOS] O
Inner Join [dbo].[PGJ_EXTRAVIOS] E on O.ID_EXTRAVIO = E.ID_EXTRAVIO AND E.FECHA_REGISTRO <= '2025-03-26T12:00:00.000'
Left Outer Join [dbo].[CAT_ESTADO_EXTRAVIO] CE on CE.ID_ESTADO_EXTRAVIO = E.ID_ESTADO_EXTRAVIO
Left Outer Join [dbo].[PGJ_HECHOS] H on H.ID_EXTRAVIO = E.ID_EXTRAVIO
Left Outer Join [dbo].[CAT_MUNICIPIO] CM ON
    CM.ID_ESTADO = 28 AND
    CM.ID_MUNICIPIO = H.ID_MUNICIPIO AND
    CM.ID_MUNICIPIO > 0
Left Outer Join [dbo].[CAT_LOCALIDAD] CL ON
    CL.ID_ESTDO = 28 AND
    CL.ID_MNCPIO = H.ID_MUNICIPIO AND
    CL.ID_LCLDD = H.ID_LOCALIDAD AND
    CL.ID_LCLDD > 0
Left Outer Join [dbo].[CAT_COLONIA] CC ON
    CC.ID_ESTDO = 28 AND
    CC.ID_MNCPIO = H.ID_MUNICIPIO AND
    CC.ID_LCLDD = H.ID_LOCALIDAD AND
    CC.ID_CLNIA = H.ID_COLONIA AND
    CC.ID_CLNIA > 0
Left Outer Join [dbo].[CAT_CALLE] CCA ON
    CCA.ID_ESTDO = 28 AND
    CCA.ID_MNCPIO = H.ID_MUNICIPIO AND
    CCA.ID_LCLDD = H.ID_LOCALIDAD AND
    CCA.ID_CLLE = H.ID_CALLE AND
    CCA.ID_CLLE > 0
WHERE O.ID_TIPO_DOCUMENTO IN (5,6) AND
    LEN(ISNULL(O.NUMERO_DOCUMENTO,'')) > 1 AND
    O.ESPECIFIQUE LIKE '%placa%' AND
    O.NUMERO_DOCUMENTO LIKE :plateNumber;